from .BW_Pixian import PIXIAN_CLASS_MAPPINGS, PIXIAN_DISPLAY_NAME_MAPPINGS
# from .BW_Cut_even_numbers import CUT_CLASS_MAPPINGS, CUT_CLASS_MAPPINGS
from .BW_image_overlay import OVERLAY_CLASS_MAPPINGS, OVERLAY_DISPLAY_NAME_MAPPINGS
from .BW_proportional_scaling import CONSTRAIN_CLASS_MAPPINGS, CONSTRAIN_DISPLAY_NAME_MAPPINGS
from .URLImageLoader import Image_CLASS_MAPPINGS, Image_DISPLAY_NAME_MAPPINGS
from .RandomSeed import RandomSeed_CLASS_MAPPINGS, RandomSeed_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(PIXIAN_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PIXIAN_DISPLAY_NAME_MAPPINGS)

# NODE_CLASS_MAPPINGS.update(CUT_CLASS_MAPPINGS)
# NODE_DISPLAY_NAME_MAPPINGS.update(CUT_CLASS_MAPPINGS)

NODE_CLASS_MAPPINGS.update(OVERLAY_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(OVERLAY_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(CONSTRAIN_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CONSTRAIN_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(Image_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(Image_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(RandomSeed_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RandomSeed_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
